// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OptionStatus.
const (
	OptionStatusOffline OptionStatus = "offline"
	OptionStatusOnline  OptionStatus = "online"
)

// Defines values for OptionType.
const (
	OptionTypeJson   OptionType = "json"
	OptionTypeString OptionType = "string"
)

// Defines values for OptionWriteRequestStatus.
const (
	OptionWriteRequestStatusOffline OptionWriteRequestStatus = "offline"
	OptionWriteRequestStatusOnline  OptionWriteRequestStatus = "online"
)

// Defines values for OptionWriteRequestType.
const (
	OptionWriteRequestTypeJson   OptionWriteRequestType = "json"
	OptionWriteRequestTypeString OptionWriteRequestType = "string"
)

// ApiResponseBase defines model for ApiResponseBase.
type ApiResponseBase struct {
	Msg string `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// AuthEnvelope defines model for AuthEnvelope.
type AuthEnvelope struct {
	Data AuthResponse `json:"data"`
	Msg  string       `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresAt Unix 秒级时间戳
	ExpiresAt int64 `json:"expires_at"`
	User      User  `json:"user"`
}

// File defines model for File.
type File struct {
	ContentType string `json:"content_type"`

	// Ctime Unix 秒级时间戳
	Ctime        int64  `json:"ctime"`
	Id           string `json:"id"`
	OriginalName string `json:"original_name"`
	Path         string `json:"path"`
	Size         int    `json:"size"`
	StorageName  string `json:"storage_name"`
	Uid          int64  `json:"uid"`

	// Utime Unix 秒级时间戳
	Utime int64 `json:"utime"`
}

// FileEnvelope defines model for FileEnvelope.
type FileEnvelope struct {
	Data File   `json:"data"`
	Msg  string `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// FileListEnvelope defines model for FileListEnvelope.
type FileListEnvelope struct {
	Data FileListResponse `json:"data"`
	Msg  string           `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// FileListResponse defines model for FileListResponse.
type FileListResponse struct {
	Items []File `json:"items"`
	Total int    `json:"total"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Identifier string `json:"identifier"`
	Password   string `json:"password"`
}

// MessageEnvelope defines model for MessageEnvelope.
type MessageEnvelope struct {
	Data MessageResponse `json:"data"`
	Msg  string          `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	DebugToken *string `json:"debug_token,omitempty"`
	Message    string  `json:"message"`
}

// Option defines model for Option.
type Option struct {
	// Ctime Unix 秒级时间戳
	Ctime       int64        `json:"ctime"`
	Description string       `json:"description"`
	Id          string       `json:"id"`
	IsPublic    bool         `json:"is_public"`
	OptionKey   string       `json:"option_key"`
	OptionValue string       `json:"option_value"`
	Status      OptionStatus `json:"status"`
	Type        OptionType   `json:"type"`

	// Utime Unix 秒级时间戳
	Utime int64 `json:"utime"`
}

// OptionStatus defines model for Option.Status.
type OptionStatus string

// OptionType defines model for Option.Type.
type OptionType string

// OptionEnvelope defines model for OptionEnvelope.
type OptionEnvelope struct {
	Data Option `json:"data"`
	Msg  string `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// OptionListEnvelope defines model for OptionListEnvelope.
type OptionListEnvelope struct {
	Data []Option `json:"data"`
	Msg  string   `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// OptionValueEnvelope defines model for OptionValueEnvelope.
type OptionValueEnvelope struct {
	Data OptionValueResponse `json:"data"`
	Msg  string              `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// OptionValueResponse defines model for OptionValueResponse.
type OptionValueResponse struct {
	Value string `json:"value"`
}

// OptionWriteRequest defines model for OptionWriteRequest.
type OptionWriteRequest struct {
	Description *string                  `json:"description,omitempty"`
	IsPublic    *bool                    `json:"is_public,omitempty"`
	Key         string                   `json:"key"`
	Status      OptionWriteRequestStatus `json:"status"`
	Type        OptionWriteRequestType   `json:"type"`
	Value       string                   `json:"value"`
}

// OptionWriteRequestStatus defines model for OptionWriteRequest.Status.
type OptionWriteRequestStatus string

// OptionWriteRequestType defines model for OptionWriteRequest.Type.
type OptionWriteRequestType string

// Problem defines model for Problem.
type Problem struct {
	Data    interface{} `json:"data"`
	Details string      `json:"details"`
	Msg     string      `json:"msg"`
	Status  int         `json:"status"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName    *string             `json:"display_name,omitempty"`
	Email          openapi_types.Email `json:"email"`
	Password       string              `json:"password"`
	TurnstileToken *string             `json:"turnstile_token,omitempty"`
	Username       string              `json:"username"`
}

// SystemStatusEnvelope defines model for SystemStatusEnvelope.
type SystemStatusEnvelope struct {
	Data SystemStatusResponse `json:"data"`
	Msg  string               `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// SystemStatusResponse defines model for SystemStatusResponse.
type SystemStatusResponse struct {
	Status string `json:"status"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Email          *openapi_types.Email `json:"email,omitempty"`
	NewPassword    *string              `json:"new_password,omitempty"`
	Token          string               `json:"token"`
	TurnstileToken *string              `json:"turnstile_token,omitempty"`
}

// User defines model for User.
type User struct {
	// Ctime Unix 秒级时间戳
	Ctime         int64  `json:"ctime"`
	DisplayName   string `json:"display_name"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	Role          string `json:"role"`
	Status        string `json:"status"`
	Uid           int64  `json:"uid"`
	Username      string `json:"username"`

	// Utime Unix 秒级时间戳
	Utime int64 `json:"utime"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	DisplayName   *string             `json:"display_name,omitempty"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified *bool               `json:"email_verified,omitempty"`
	Password      string              `json:"password"`
	Role          *string             `json:"role,omitempty"`
	Status        *string             `json:"status,omitempty"`
	Username      string              `json:"username"`
}

// UserEnvelope defines model for UserEnvelope.
type UserEnvelope struct {
	Data User   `json:"data"`
	Msg  string `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// UserListEnvelope defines model for UserListEnvelope.
type UserListEnvelope struct {
	Data UserListResponse `json:"data"`
	Msg  string           `json:"msg"`

	// Status 0 表示成功；100000-199999 为系统级状态码；200000-299999 为业务级状态码，按 biz 模块分段
	Status int `json:"status"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Items []User `json:"items"`
	Total int    `json:"total"`
}

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	DisplayName   *string              `json:"display_name,omitempty"`
	Email         *openapi_types.Email `json:"email,omitempty"`
	EmailVerified *bool                `json:"email_verified,omitempty"`
	Password      *string              `json:"password,omitempty"`
	Role          *string              `json:"role,omitempty"`
	Status        *string              `json:"status,omitempty"`
}

// ProblemResponse defines model for ProblemResponse.
type ProblemResponse = Problem

// GetFilesSearchParams defines parameters for GetFilesSearch.
type GetFilesSearchParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// PostFilesUploadMultipartBody defines parameters for PostFilesUpload.
type PostFilesUploadMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// PutUsersMeJSONBody defines parameters for PutUsersMe.
type PutUsersMeJSONBody struct {
	DisplayName *string `json:"display_name,omitempty"`
}

// GetUsersSearchParams defines parameters for GetUsersSearch.
type GetUsersSearchParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// PostAuthEmailVerifyJSONRequestBody defines body for PostAuthEmailVerify for application/json ContentType.
type PostAuthEmailVerifyJSONRequestBody = TokenRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthPasswordRequestResetJSONRequestBody defines body for PostAuthPasswordRequestReset for application/json ContentType.
type PostAuthPasswordRequestResetJSONRequestBody = TokenRequest

// PostAuthPasswordResetJSONRequestBody defines body for PostAuthPasswordReset for application/json ContentType.
type PostAuthPasswordResetJSONRequestBody = TokenRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostFilesUploadMultipartRequestBody defines body for PostFilesUpload for multipart/form-data ContentType.
type PostFilesUploadMultipartRequestBody PostFilesUploadMultipartBody

// PostOptionsJSONRequestBody defines body for PostOptions for application/json ContentType.
type PostOptionsJSONRequestBody = OptionWriteRequest

// PutOptionsJSONRequestBody defines body for PutOptions for application/json ContentType.
type PutOptionsJSONRequestBody = OptionWriteRequest

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserCreateRequest

// PutUsersMeJSONRequestBody defines body for PutUsersMe for application/json ContentType.
type PutUsersMeJSONRequestBody PutUsersMeJSONBody

// PutUsersIdJSONRequestBody defines body for PutUsersId for application/json ContentType.
type PutUsersIdJSONRequestBody = UserUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/email/send-verification)
	PostAuthEmailSendVerification(c *gin.Context)

	// (POST /auth/email/verify)
	PostAuthEmailVerify(c *gin.Context)

	// (POST /auth/login)
	PostAuthLogin(c *gin.Context)

	// (POST /auth/logout)
	PostAuthLogout(c *gin.Context)

	// (POST /auth/password/request-reset)
	PostAuthPasswordRequestReset(c *gin.Context)

	// (POST /auth/password/reset)
	PostAuthPasswordReset(c *gin.Context)

	// (POST /auth/refresh)
	PostAuthRefresh(c *gin.Context)

	// (POST /auth/register)
	PostAuthRegister(c *gin.Context)

	// (GET /files)
	GetFiles(c *gin.Context)

	// (GET /files/search)
	GetFilesSearch(c *gin.Context, params GetFilesSearchParams)

	// (POST /files/upload)
	PostFilesUpload(c *gin.Context)

	// (DELETE /files/{id})
	DeleteFilesId(c *gin.Context, id string)

	// (GET /files/{id})
	GetFilesId(c *gin.Context, id string)

	// (GET /options)
	GetOptions(c *gin.Context)

	// (POST /options)
	PostOptions(c *gin.Context)

	// (PUT /options)
	PutOptions(c *gin.Context)

	// (GET /system/about)
	GetSystemAbout(c *gin.Context)

	// (GET /system/notice)
	GetSystemNotice(c *gin.Context)

	// (GET /system/status)
	GetSystemStatus(c *gin.Context)

	// (GET /users)
	GetUsers(c *gin.Context, params GetUsersParams)

	// (POST /users)
	PostUsers(c *gin.Context)

	// (GET /users/me)
	GetUsersMe(c *gin.Context)

	// (PUT /users/me)
	PutUsersMe(c *gin.Context)

	// (GET /users/search)
	GetUsersSearch(c *gin.Context, params GetUsersSearchParams)

	// (DELETE /users/{id})
	DeleteUsersId(c *gin.Context, id string)

	// (GET /users/{id})
	GetUsersId(c *gin.Context, id string)

	// (PUT /users/{id})
	PutUsersId(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuthEmailSendVerification operation middleware
func (siw *ServerInterfaceWrapper) PostAuthEmailSendVerification(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthEmailSendVerification(c)
}

// PostAuthEmailVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAuthEmailVerify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthEmailVerify(c)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthLogin(c)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthLogout(c)
}

// PostAuthPasswordRequestReset operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordRequestReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthPasswordRequestReset(c)
}

// PostAuthPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthPasswordReset(c)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthRefresh(c)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthRegister(c)
}

// GetFiles operation middleware
func (siw *ServerInterfaceWrapper) GetFiles(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFiles(c)
}

// GetFilesSearch operation middleware
func (siw *ServerInterfaceWrapper) GetFilesSearch(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFilesSearchParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFilesSearch(c, params)
}

// PostFilesUpload operation middleware
func (siw *ServerInterfaceWrapper) PostFilesUpload(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostFilesUpload(c)
}

// DeleteFilesId operation middleware
func (siw *ServerInterfaceWrapper) DeleteFilesId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteFilesId(c, id)
}

// GetFilesId operation middleware
func (siw *ServerInterfaceWrapper) GetFilesId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFilesId(c, id)
}

// GetOptions operation middleware
func (siw *ServerInterfaceWrapper) GetOptions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOptions(c)
}

// PostOptions operation middleware
func (siw *ServerInterfaceWrapper) PostOptions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostOptions(c)
}

// PutOptions operation middleware
func (siw *ServerInterfaceWrapper) PutOptions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutOptions(c)
}

// GetSystemAbout operation middleware
func (siw *ServerInterfaceWrapper) GetSystemAbout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemAbout(c)
}

// GetSystemNotice operation middleware
func (siw *ServerInterfaceWrapper) GetSystemNotice(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemNotice(c)
}

// GetSystemStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSystemStatus(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSystemStatus(c)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsers(c, params)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsers(c)
}

// GetUsersMe operation middleware
func (siw *ServerInterfaceWrapper) GetUsersMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersMe(c)
}

// PutUsersMe operation middleware
func (siw *ServerInterfaceWrapper) PutUsersMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutUsersMe(c)
}

// GetUsersSearch operation middleware
func (siw *ServerInterfaceWrapper) GetUsersSearch(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersSearchParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersSearch(c, params)
}

// DeleteUsersId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteUsersId(c, id)
}

// GetUsersId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersId(c, id)
}

// PutUsersId operation middleware
func (siw *ServerInterfaceWrapper) PutUsersId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutUsersId(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/email/send-verification", wrapper.PostAuthEmailSendVerification)
	router.POST(options.BaseURL+"/auth/email/verify", wrapper.PostAuthEmailVerify)
	router.POST(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	router.POST(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	router.POST(options.BaseURL+"/auth/password/request-reset", wrapper.PostAuthPasswordRequestReset)
	router.POST(options.BaseURL+"/auth/password/reset", wrapper.PostAuthPasswordReset)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	router.POST(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	router.GET(options.BaseURL+"/files", wrapper.GetFiles)
	router.GET(options.BaseURL+"/files/search", wrapper.GetFilesSearch)
	router.POST(options.BaseURL+"/files/upload", wrapper.PostFilesUpload)
	router.DELETE(options.BaseURL+"/files/:id", wrapper.DeleteFilesId)
	router.GET(options.BaseURL+"/files/:id", wrapper.GetFilesId)
	router.GET(options.BaseURL+"/options", wrapper.GetOptions)
	router.POST(options.BaseURL+"/options", wrapper.PostOptions)
	router.PUT(options.BaseURL+"/options", wrapper.PutOptions)
	router.GET(options.BaseURL+"/system/about", wrapper.GetSystemAbout)
	router.GET(options.BaseURL+"/system/notice", wrapper.GetSystemNotice)
	router.GET(options.BaseURL+"/system/status", wrapper.GetSystemStatus)
	router.GET(options.BaseURL+"/users", wrapper.GetUsers)
	router.POST(options.BaseURL+"/users", wrapper.PostUsers)
	router.GET(options.BaseURL+"/users/me", wrapper.GetUsersMe)
	router.PUT(options.BaseURL+"/users/me", wrapper.PutUsersMe)
	router.GET(options.BaseURL+"/users/search", wrapper.GetUsersSearch)
	router.DELETE(options.BaseURL+"/users/:id", wrapper.DeleteUsersId)
	router.GET(options.BaseURL+"/users/:id", wrapper.GetUsersId)
	router.PUT(options.BaseURL+"/users/:id", wrapper.PutUsersId)
}

type ProblemResponseJSONResponse Problem

type PostAuthEmailSendVerificationRequestObject struct {
}

type PostAuthEmailSendVerificationResponseObject interface {
	VisitPostAuthEmailSendVerificationResponse(w http.ResponseWriter) error
}

type PostAuthEmailSendVerification200JSONResponse MessageEnvelope

func (response PostAuthEmailSendVerification200JSONResponse) VisitPostAuthEmailSendVerificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthEmailSendVerificationdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostAuthEmailSendVerificationdefaultJSONResponse) VisitPostAuthEmailSendVerificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthEmailVerifyRequestObject struct {
	Body *PostAuthEmailVerifyJSONRequestBody
}

type PostAuthEmailVerifyResponseObject interface {
	VisitPostAuthEmailVerifyResponse(w http.ResponseWriter) error
}

type PostAuthEmailVerify200JSONResponse MessageEnvelope

func (response PostAuthEmailVerify200JSONResponse) VisitPostAuthEmailVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthEmailVerifydefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostAuthEmailVerifydefaultJSONResponse) VisitPostAuthEmailVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthLoginRequestObject struct {
	Body *PostAuthLoginJSONRequestBody
}

type PostAuthLoginResponseObject interface {
	VisitPostAuthLoginResponse(w http.ResponseWriter) error
}

type PostAuthLogin200JSONResponse AuthEnvelope

func (response PostAuthLogin200JSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthLogindefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostAuthLogindefaultJSONResponse) VisitPostAuthLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthLogoutRequestObject struct {
}

type PostAuthLogoutResponseObject interface {
	VisitPostAuthLogoutResponse(w http.ResponseWriter) error
}

type PostAuthLogout200JSONResponse MessageEnvelope

func (response PostAuthLogout200JSONResponse) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthLogoutdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostAuthLogoutdefaultJSONResponse) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthPasswordRequestResetRequestObject struct {
	Body *PostAuthPasswordRequestResetJSONRequestBody
}

type PostAuthPasswordRequestResetResponseObject interface {
	VisitPostAuthPasswordRequestResetResponse(w http.ResponseWriter) error
}

type PostAuthPasswordRequestReset200JSONResponse MessageEnvelope

func (response PostAuthPasswordRequestReset200JSONResponse) VisitPostAuthPasswordRequestResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthPasswordRequestResetdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostAuthPasswordRequestResetdefaultJSONResponse) VisitPostAuthPasswordRequestResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthPasswordResetRequestObject struct {
	Body *PostAuthPasswordResetJSONRequestBody
}

type PostAuthPasswordResetResponseObject interface {
	VisitPostAuthPasswordResetResponse(w http.ResponseWriter) error
}

type PostAuthPasswordReset200JSONResponse MessageEnvelope

func (response PostAuthPasswordReset200JSONResponse) VisitPostAuthPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthPasswordResetdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostAuthPasswordResetdefaultJSONResponse) VisitPostAuthPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthRefreshRequestObject struct {
}

type PostAuthRefreshResponseObject interface {
	VisitPostAuthRefreshResponse(w http.ResponseWriter) error
}

type PostAuthRefresh200JSONResponse AuthEnvelope

func (response PostAuthRefresh200JSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthRefreshdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostAuthRefreshdefaultJSONResponse) VisitPostAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthRegisterRequestObject struct {
	Body *PostAuthRegisterJSONRequestBody
}

type PostAuthRegisterResponseObject interface {
	VisitPostAuthRegisterResponse(w http.ResponseWriter) error
}

type PostAuthRegister200JSONResponse AuthEnvelope

func (response PostAuthRegister200JSONResponse) VisitPostAuthRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthRegisterdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostAuthRegisterdefaultJSONResponse) VisitPostAuthRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetFilesRequestObject struct {
}

type GetFilesResponseObject interface {
	VisitGetFilesResponse(w http.ResponseWriter) error
}

type GetFiles200JSONResponse FileListEnvelope

func (response GetFiles200JSONResponse) VisitGetFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFilesdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetFilesdefaultJSONResponse) VisitGetFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetFilesSearchRequestObject struct {
	Params GetFilesSearchParams
}

type GetFilesSearchResponseObject interface {
	VisitGetFilesSearchResponse(w http.ResponseWriter) error
}

type GetFilesSearch200JSONResponse FileListEnvelope

func (response GetFilesSearch200JSONResponse) VisitGetFilesSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFilesSearchdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetFilesSearchdefaultJSONResponse) VisitGetFilesSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostFilesUploadRequestObject struct {
	Body *multipart.Reader
}

type PostFilesUploadResponseObject interface {
	VisitPostFilesUploadResponse(w http.ResponseWriter) error
}

type PostFilesUpload200JSONResponse FileEnvelope

func (response PostFilesUpload200JSONResponse) VisitPostFilesUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostFilesUploaddefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostFilesUploaddefaultJSONResponse) VisitPostFilesUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteFilesIdRequestObject struct {
	Id string `json:"id"`
}

type DeleteFilesIdResponseObject interface {
	VisitDeleteFilesIdResponse(w http.ResponseWriter) error
}

type DeleteFilesId200JSONResponse MessageEnvelope

func (response DeleteFilesId200JSONResponse) VisitDeleteFilesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFilesIddefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteFilesIddefaultJSONResponse) VisitDeleteFilesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetFilesIdRequestObject struct {
	Id string `json:"id"`
}

type GetFilesIdResponseObject interface {
	VisitGetFilesIdResponse(w http.ResponseWriter) error
}

type GetFilesId200JSONResponse FileEnvelope

func (response GetFilesId200JSONResponse) VisitGetFilesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFilesIddefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetFilesIddefaultJSONResponse) VisitGetFilesIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOptionsRequestObject struct {
}

type GetOptionsResponseObject interface {
	VisitGetOptionsResponse(w http.ResponseWriter) error
}

type GetOptions200JSONResponse OptionListEnvelope

func (response GetOptions200JSONResponse) VisitGetOptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOptionsdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetOptionsdefaultJSONResponse) VisitGetOptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostOptionsRequestObject struct {
	Body *PostOptionsJSONRequestBody
}

type PostOptionsResponseObject interface {
	VisitPostOptionsResponse(w http.ResponseWriter) error
}

type PostOptions200JSONResponse OptionEnvelope

func (response PostOptions200JSONResponse) VisitPostOptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostOptionsdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostOptionsdefaultJSONResponse) VisitPostOptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PutOptionsRequestObject struct {
	Body *PutOptionsJSONRequestBody
}

type PutOptionsResponseObject interface {
	VisitPutOptionsResponse(w http.ResponseWriter) error
}

type PutOptions200JSONResponse OptionEnvelope

func (response PutOptions200JSONResponse) VisitPutOptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutOptionsdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PutOptionsdefaultJSONResponse) VisitPutOptionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSystemAboutRequestObject struct {
}

type GetSystemAboutResponseObject interface {
	VisitGetSystemAboutResponse(w http.ResponseWriter) error
}

type GetSystemAbout200JSONResponse OptionValueEnvelope

func (response GetSystemAbout200JSONResponse) VisitGetSystemAboutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSystemAboutdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSystemAboutdefaultJSONResponse) VisitGetSystemAboutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSystemNoticeRequestObject struct {
}

type GetSystemNoticeResponseObject interface {
	VisitGetSystemNoticeResponse(w http.ResponseWriter) error
}

type GetSystemNotice200JSONResponse OptionValueEnvelope

func (response GetSystemNotice200JSONResponse) VisitGetSystemNoticeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSystemNoticedefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSystemNoticedefaultJSONResponse) VisitGetSystemNoticeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSystemStatusRequestObject struct {
}

type GetSystemStatusResponseObject interface {
	VisitGetSystemStatusResponse(w http.ResponseWriter) error
}

type GetSystemStatus200JSONResponse SystemStatusEnvelope

func (response GetSystemStatus200JSONResponse) VisitGetSystemStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSystemStatusdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSystemStatusdefaultJSONResponse) VisitGetSystemStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetUsersRequestObject struct {
	Params GetUsersParams
}

type GetUsersResponseObject interface {
	VisitGetUsersResponse(w http.ResponseWriter) error
}

type GetUsers200JSONResponse UserListEnvelope

func (response GetUsers200JSONResponse) VisitGetUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetUsersdefaultJSONResponse) VisitGetUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostUsersRequestObject struct {
	Body *PostUsersJSONRequestBody
}

type PostUsersResponseObject interface {
	VisitPostUsersResponse(w http.ResponseWriter) error
}

type PostUsers200JSONResponse UserEnvelope

func (response PostUsers200JSONResponse) VisitPostUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PostUsersdefaultJSONResponse) VisitPostUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetUsersMeRequestObject struct {
}

type GetUsersMeResponseObject interface {
	VisitGetUsersMeResponse(w http.ResponseWriter) error
}

type GetUsersMe200JSONResponse UserEnvelope

func (response GetUsersMe200JSONResponse) VisitGetUsersMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersMedefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetUsersMedefaultJSONResponse) VisitGetUsersMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PutUsersMeRequestObject struct {
	Body *PutUsersMeJSONRequestBody
}

type PutUsersMeResponseObject interface {
	VisitPutUsersMeResponse(w http.ResponseWriter) error
}

type PutUsersMe200JSONResponse UserEnvelope

func (response PutUsersMe200JSONResponse) VisitPutUsersMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersMedefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PutUsersMedefaultJSONResponse) VisitPutUsersMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetUsersSearchRequestObject struct {
	Params GetUsersSearchParams
}

type GetUsersSearchResponseObject interface {
	VisitGetUsersSearchResponse(w http.ResponseWriter) error
}

type GetUsersSearch200JSONResponse UserListEnvelope

func (response GetUsersSearch200JSONResponse) VisitGetUsersSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersSearchdefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetUsersSearchdefaultJSONResponse) VisitGetUsersSearchResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteUsersIdRequestObject struct {
	Id string `json:"id"`
}

type DeleteUsersIdResponseObject interface {
	VisitDeleteUsersIdResponse(w http.ResponseWriter) error
}

type DeleteUsersId200JSONResponse MessageEnvelope

func (response DeleteUsersId200JSONResponse) VisitDeleteUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUsersIddefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteUsersIddefaultJSONResponse) VisitDeleteUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetUsersIdRequestObject struct {
	Id string `json:"id"`
}

type GetUsersIdResponseObject interface {
	VisitGetUsersIdResponse(w http.ResponseWriter) error
}

type GetUsersId200JSONResponse UserEnvelope

func (response GetUsersId200JSONResponse) VisitGetUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersIddefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetUsersIddefaultJSONResponse) VisitGetUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PutUsersIdRequestObject struct {
	Id   string `json:"id"`
	Body *PutUsersIdJSONRequestBody
}

type PutUsersIdResponseObject interface {
	VisitPutUsersIdResponse(w http.ResponseWriter) error
}

type PutUsersId200JSONResponse UserEnvelope

func (response PutUsersId200JSONResponse) VisitPutUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutUsersIddefaultJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PutUsersIddefaultJSONResponse) VisitPutUsersIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/email/send-verification)
	PostAuthEmailSendVerification(ctx context.Context, request PostAuthEmailSendVerificationRequestObject) (PostAuthEmailSendVerificationResponseObject, error)

	// (POST /auth/email/verify)
	PostAuthEmailVerify(ctx context.Context, request PostAuthEmailVerifyRequestObject) (PostAuthEmailVerifyResponseObject, error)

	// (POST /auth/login)
	PostAuthLogin(ctx context.Context, request PostAuthLoginRequestObject) (PostAuthLoginResponseObject, error)

	// (POST /auth/logout)
	PostAuthLogout(ctx context.Context, request PostAuthLogoutRequestObject) (PostAuthLogoutResponseObject, error)

	// (POST /auth/password/request-reset)
	PostAuthPasswordRequestReset(ctx context.Context, request PostAuthPasswordRequestResetRequestObject) (PostAuthPasswordRequestResetResponseObject, error)

	// (POST /auth/password/reset)
	PostAuthPasswordReset(ctx context.Context, request PostAuthPasswordResetRequestObject) (PostAuthPasswordResetResponseObject, error)

	// (POST /auth/refresh)
	PostAuthRefresh(ctx context.Context, request PostAuthRefreshRequestObject) (PostAuthRefreshResponseObject, error)

	// (POST /auth/register)
	PostAuthRegister(ctx context.Context, request PostAuthRegisterRequestObject) (PostAuthRegisterResponseObject, error)

	// (GET /files)
	GetFiles(ctx context.Context, request GetFilesRequestObject) (GetFilesResponseObject, error)

	// (GET /files/search)
	GetFilesSearch(ctx context.Context, request GetFilesSearchRequestObject) (GetFilesSearchResponseObject, error)

	// (POST /files/upload)
	PostFilesUpload(ctx context.Context, request PostFilesUploadRequestObject) (PostFilesUploadResponseObject, error)

	// (DELETE /files/{id})
	DeleteFilesId(ctx context.Context, request DeleteFilesIdRequestObject) (DeleteFilesIdResponseObject, error)

	// (GET /files/{id})
	GetFilesId(ctx context.Context, request GetFilesIdRequestObject) (GetFilesIdResponseObject, error)

	// (GET /options)
	GetOptions(ctx context.Context, request GetOptionsRequestObject) (GetOptionsResponseObject, error)

	// (POST /options)
	PostOptions(ctx context.Context, request PostOptionsRequestObject) (PostOptionsResponseObject, error)

	// (PUT /options)
	PutOptions(ctx context.Context, request PutOptionsRequestObject) (PutOptionsResponseObject, error)

	// (GET /system/about)
	GetSystemAbout(ctx context.Context, request GetSystemAboutRequestObject) (GetSystemAboutResponseObject, error)

	// (GET /system/notice)
	GetSystemNotice(ctx context.Context, request GetSystemNoticeRequestObject) (GetSystemNoticeResponseObject, error)

	// (GET /system/status)
	GetSystemStatus(ctx context.Context, request GetSystemStatusRequestObject) (GetSystemStatusResponseObject, error)

	// (GET /users)
	GetUsers(ctx context.Context, request GetUsersRequestObject) (GetUsersResponseObject, error)

	// (POST /users)
	PostUsers(ctx context.Context, request PostUsersRequestObject) (PostUsersResponseObject, error)

	// (GET /users/me)
	GetUsersMe(ctx context.Context, request GetUsersMeRequestObject) (GetUsersMeResponseObject, error)

	// (PUT /users/me)
	PutUsersMe(ctx context.Context, request PutUsersMeRequestObject) (PutUsersMeResponseObject, error)

	// (GET /users/search)
	GetUsersSearch(ctx context.Context, request GetUsersSearchRequestObject) (GetUsersSearchResponseObject, error)

	// (DELETE /users/{id})
	DeleteUsersId(ctx context.Context, request DeleteUsersIdRequestObject) (DeleteUsersIdResponseObject, error)

	// (GET /users/{id})
	GetUsersId(ctx context.Context, request GetUsersIdRequestObject) (GetUsersIdResponseObject, error)

	// (PUT /users/{id})
	PutUsersId(ctx context.Context, request PutUsersIdRequestObject) (PutUsersIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostAuthEmailSendVerification operation middleware
func (sh *strictHandler) PostAuthEmailSendVerification(ctx *gin.Context) {
	var request PostAuthEmailSendVerificationRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthEmailSendVerification(ctx, request.(PostAuthEmailSendVerificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthEmailSendVerification")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthEmailSendVerificationResponseObject); ok {
		if err := validResponse.VisitPostAuthEmailSendVerificationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthEmailVerify operation middleware
func (sh *strictHandler) PostAuthEmailVerify(ctx *gin.Context) {
	var request PostAuthEmailVerifyRequestObject

	var body PostAuthEmailVerifyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthEmailVerify(ctx, request.(PostAuthEmailVerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthEmailVerify")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthEmailVerifyResponseObject); ok {
		if err := validResponse.VisitPostAuthEmailVerifyResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogin operation middleware
func (sh *strictHandler) PostAuthLogin(ctx *gin.Context) {
	var request PostAuthLoginRequestObject

	var body PostAuthLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogin(ctx, request.(PostAuthLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthLoginResponseObject); ok {
		if err := validResponse.VisitPostAuthLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogout operation middleware
func (sh *strictHandler) PostAuthLogout(ctx *gin.Context) {
	var request PostAuthLogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogout(ctx, request.(PostAuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthLogoutResponseObject); ok {
		if err := validResponse.VisitPostAuthLogoutResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthPasswordRequestReset operation middleware
func (sh *strictHandler) PostAuthPasswordRequestReset(ctx *gin.Context) {
	var request PostAuthPasswordRequestResetRequestObject

	var body PostAuthPasswordRequestResetJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthPasswordRequestReset(ctx, request.(PostAuthPasswordRequestResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthPasswordRequestReset")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthPasswordRequestResetResponseObject); ok {
		if err := validResponse.VisitPostAuthPasswordRequestResetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthPasswordReset operation middleware
func (sh *strictHandler) PostAuthPasswordReset(ctx *gin.Context) {
	var request PostAuthPasswordResetRequestObject

	var body PostAuthPasswordResetJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthPasswordReset(ctx, request.(PostAuthPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthPasswordReset")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthPasswordResetResponseObject); ok {
		if err := validResponse.VisitPostAuthPasswordResetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthRefresh operation middleware
func (sh *strictHandler) PostAuthRefresh(ctx *gin.Context) {
	var request PostAuthRefreshRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthRefresh(ctx, request.(PostAuthRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthRefresh")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthRefreshResponseObject); ok {
		if err := validResponse.VisitPostAuthRefreshResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthRegister operation middleware
func (sh *strictHandler) PostAuthRegister(ctx *gin.Context) {
	var request PostAuthRegisterRequestObject

	var body PostAuthRegisterJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthRegister(ctx, request.(PostAuthRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthRegister")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostAuthRegisterResponseObject); ok {
		if err := validResponse.VisitPostAuthRegisterResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFiles operation middleware
func (sh *strictHandler) GetFiles(ctx *gin.Context) {
	var request GetFilesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetFiles(ctx, request.(GetFilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFiles")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetFilesResponseObject); ok {
		if err := validResponse.VisitGetFilesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFilesSearch operation middleware
func (sh *strictHandler) GetFilesSearch(ctx *gin.Context, params GetFilesSearchParams) {
	var request GetFilesSearchRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetFilesSearch(ctx, request.(GetFilesSearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFilesSearch")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetFilesSearchResponseObject); ok {
		if err := validResponse.VisitGetFilesSearchResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostFilesUpload operation middleware
func (sh *strictHandler) PostFilesUpload(ctx *gin.Context) {
	var request PostFilesUploadRequestObject

	if reader, err := ctx.Request.MultipartReader(); err == nil {
		request.Body = reader
	} else {
		ctx.Error(err)
		return
	}

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostFilesUpload(ctx, request.(PostFilesUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFilesUpload")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostFilesUploadResponseObject); ok {
		if err := validResponse.VisitPostFilesUploadResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFilesId operation middleware
func (sh *strictHandler) DeleteFilesId(ctx *gin.Context, id string) {
	var request DeleteFilesIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFilesId(ctx, request.(DeleteFilesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFilesId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteFilesIdResponseObject); ok {
		if err := validResponse.VisitDeleteFilesIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFilesId operation middleware
func (sh *strictHandler) GetFilesId(ctx *gin.Context, id string) {
	var request GetFilesIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetFilesId(ctx, request.(GetFilesIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFilesId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetFilesIdResponseObject); ok {
		if err := validResponse.VisitGetFilesIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOptions operation middleware
func (sh *strictHandler) GetOptions(ctx *gin.Context) {
	var request GetOptionsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOptions(ctx, request.(GetOptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOptions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetOptionsResponseObject); ok {
		if err := validResponse.VisitGetOptionsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostOptions operation middleware
func (sh *strictHandler) PostOptions(ctx *gin.Context) {
	var request PostOptionsRequestObject

	var body PostOptionsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostOptions(ctx, request.(PostOptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostOptions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostOptionsResponseObject); ok {
		if err := validResponse.VisitPostOptionsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutOptions operation middleware
func (sh *strictHandler) PutOptions(ctx *gin.Context) {
	var request PutOptionsRequestObject

	var body PutOptionsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutOptions(ctx, request.(PutOptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutOptions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutOptionsResponseObject); ok {
		if err := validResponse.VisitPutOptionsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystemAbout operation middleware
func (sh *strictHandler) GetSystemAbout(ctx *gin.Context) {
	var request GetSystemAboutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystemAbout(ctx, request.(GetSystemAboutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystemAbout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSystemAboutResponseObject); ok {
		if err := validResponse.VisitGetSystemAboutResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystemNotice operation middleware
func (sh *strictHandler) GetSystemNotice(ctx *gin.Context) {
	var request GetSystemNoticeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystemNotice(ctx, request.(GetSystemNoticeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystemNotice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSystemNoticeResponseObject); ok {
		if err := validResponse.VisitGetSystemNoticeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystemStatus operation middleware
func (sh *strictHandler) GetSystemStatus(ctx *gin.Context) {
	var request GetSystemStatusRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystemStatus(ctx, request.(GetSystemStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystemStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSystemStatusResponseObject); ok {
		if err := validResponse.VisitGetSystemStatusResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsers operation middleware
func (sh *strictHandler) GetUsers(ctx *gin.Context, params GetUsersParams) {
	var request GetUsersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsers(ctx, request.(GetUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsersResponseObject); ok {
		if err := validResponse.VisitGetUsersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUsers operation middleware
func (sh *strictHandler) PostUsers(ctx *gin.Context) {
	var request PostUsersRequestObject

	var body PostUsersJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsers(ctx, request.(PostUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostUsersResponseObject); ok {
		if err := validResponse.VisitPostUsersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsersMe operation middleware
func (sh *strictHandler) GetUsersMe(ctx *gin.Context) {
	var request GetUsersMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersMe(ctx, request.(GetUsersMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsersMeResponseObject); ok {
		if err := validResponse.VisitGetUsersMeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutUsersMe operation middleware
func (sh *strictHandler) PutUsersMe(ctx *gin.Context) {
	var request PutUsersMeRequestObject

	var body PutUsersMeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutUsersMe(ctx, request.(PutUsersMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutUsersMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutUsersMeResponseObject); ok {
		if err := validResponse.VisitPutUsersMeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsersSearch operation middleware
func (sh *strictHandler) GetUsersSearch(ctx *gin.Context, params GetUsersSearchParams) {
	var request GetUsersSearchRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersSearch(ctx, request.(GetUsersSearchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersSearch")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsersSearchResponseObject); ok {
		if err := validResponse.VisitGetUsersSearchResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteUsersId operation middleware
func (sh *strictHandler) DeleteUsersId(ctx *gin.Context, id string) {
	var request DeleteUsersIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUsersId(ctx, request.(DeleteUsersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUsersId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteUsersIdResponseObject); ok {
		if err := validResponse.VisitDeleteUsersIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsersId operation middleware
func (sh *strictHandler) GetUsersId(ctx *gin.Context, id string) {
	var request GetUsersIdRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersId(ctx, request.(GetUsersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsersIdResponseObject); ok {
		if err := validResponse.VisitGetUsersIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutUsersId operation middleware
func (sh *strictHandler) PutUsersId(ctx *gin.Context, id string) {
	var request PutUsersIdRequestObject

	request.Id = id

	var body PutUsersIdJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutUsersId(ctx, request.(PutUsersIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutUsersId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PutUsersIdResponseObject); ok {
		if err := validResponse.VisitPutUsersIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
